replicaCount: 1
image:
  repository: ltrungtrieu/landing
  tag: dev
imagePullPolicy: Always

resources:
  limits:
    cpu: "1"
    memory: "2Gi"
  requests:
    cpu: "0.1"
    memory: "512Mi"

hostname: 

serviceAccount:
  create: true
  name: "webpage"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80